
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/type: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/type: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/type: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullsecretname }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: GROQ_API_KEY

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_PASSWORD








            - name: LLM_BACKEND
              value: "{{ .Values.env.LLM_BACKEND }}"

            - name: ACTIVE_MODEL
              value: "{{ .Values.env.ACTIVE_MODEL }}"

            - name: MODELS_TO_PULL
              value: "{{ .Values.env.MODELS_TO_PULL }}"

            - name: POSTGRES_HOST
              value: "{{ .Values.env.POSTGRES_HOST }}"

            - name: POSTGRES_PORT
              value: "{{ .Values.env.POSTGRES_PORT }}"

            - name: OLLAMA_BASE_URL
              value: "{{ .Values.env.OLLAMA_BASE_URL }}"
            
            - name: POSTGRES_DB
              value: "{{ .Values.env.POSTGRES_DB }}"

            
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
